name: Diagbox (build)
on:
  workflow_dispatch:
  push:
  
jobs:
   build:
    runs-on: windows-latest
    #container: dockcross/windows-static-x64:latest
    
    steps:       
        - uses: actions/checkout@v2
    
        - name: Set up MinGW
          uses: egor-tensin/setup-mingw@v2
          with:
            platform: x64

        - name: Compile windows version with cross-compilator
          run: |
             make
             dir
             
