name: Diagbox (build)
on:
  workflow_dispatch:
  push:

 jobs:
  build:
    runs-on: windows
    container: dockcross/windows-static-x64:latest
    
    steps:       
        - uses: actions/checkout@v2
    
        - name: Compile windows version with cross-compilator
           run: |
             Make
             dir
             