name: Release Diagbox
on:
  workflow_dispatch:
  push:
    paths:
      - 'bin/*bits/*.*'
      - '.github/workflows/*.yml'
      - '**.cpp'
      - '**.rc'
      - '**.h'
      - '**CMakeLists.txt'

jobs:
  Build_and_Repack:
   strategy:
    matrix:
      DOCKER: ["dockcross/windows-static-x86:latest","dockcross/windows-static-x64:latest"]
   runs-on: ubuntu-latest
   container: ${{ matrix.DOCKER}}
   steps:

    - name: checkout code for release
      uses: actions/checkout@v2

    - name: build
      run: |
        echo ${{matrix.DOCKER}} |grep "x[0-9][0-9]" >TMP.TXT
        BLD=$(cat TMP.TXT)
        mkdir build
        cd build
        cmake ..
        make clean all
        cp DiagBox.exe ../bin/$BLD/DiagBox.exe

    - name: Zip Folder
      run: |
        SCH=${GITHUB_SHA::7}
        BLD=$(cat TMP.TXT)
        cd bin
        cd $BLD
        echo commit $SCH>commit.txt
        echo `date`>>commit.txt
        cd ..
        DATEE=`date '+[%Y-%m-%d]'`
        mv $BLD DiagBox$DATEE-\[$BLD\]
        7z a -t7z -r  DiagBox\[$SCH\]-$BLD.7z DiagBox*/*
        ls -R

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: DiagBox
        path: |
             bin/*.7z

  Release:
   needs: Build_and_Repack
   runs-on: ubuntu-latest
   steps:

    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: Latest
        prerelease: true
        title: latest build
        files: |
                bin/*.7z
