name: Release Diagbox
on:
  workflow_dispatch:
  push:
    paths:
      - 'bin/*bits/*.*'
      - '.github/workflows/*.yml'

  #schedule:
  # - cron: "0 15 * * *"
jobs:
  Repack_and_Release:
   strategy:
    matrix:
      build_target: [64-bits,32-bits]
   runs-on: ubuntu-latest
   steps:

    - name: checkout code for release
      uses: actions/checkout@v1

    - name: Zip Folder
      run: |
        SCH=${GITHUB_SHA::7}
        BLD="${{ matrix.build_target }}"
        cd bin
        cd $BLD
        echo commit $SCH>commit.sys
        echo `date`>>commit.sys
        cd ..
        DATEE=`date '+[%Y-%m-%d]'`
        mv $BLD DiagBox$DATEE-\[$BLD\]
        zip -r DiagBox\[$SCH\]-$BLD DiagBox*/*
        ls -R
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: DiagBox
        path: |
             bin/*.zip
             
    - name: Create release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{matrix.build_target}}
        prerelease: true
        title: ${{matrix.build_target}}
        files: |
                bin/*.zip
