name: ubuntu-codeblocks

on: 
  push:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: apt-get update
      run: sudo apt-get update -y

    - name: apt-get install -y codeblocks
      run: sudo apt-get install -y codeblocks

    - name: codeblocks's default configuration
      run: |
        mkdir -p ~/.config/codeblocks
        cp codeblocks/default.conf ~/.config/codeblocks/

    - name: build projects
      uses: GabrielBB/xvfb-action@v1 # fake X-server as codeblocks requires displays :/
      with:
        run: codeblocks --no-splash-screen --target=Release --rebuild DiagBox.cbp
 
